version: '3'

services:
  postgres: 
    image: 'postgres:alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - 'postgresql_data:/alpine/postgresql'
      
networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local